# Generated by Django 5.0.6 on 2024-08-19 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('present_address', models.CharField(max_length=255)),
                ('home_address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
