# Generated by Django 5.0.7 on 2024-10-17 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='appointment_time',
            field=models.TimeField(default=datetime.date.today),
        ),
    ]
