# Generated by Django 5.0.7 on 2024-10-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='userappointment',
            name='appointment_time',
        ),
    ]
