# Generated by Django 5.0.7 on 2024-10-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alangilanusers',
            name='user',
        ),
    ]
