# Generated by Django 5.0.7 on 2024-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userappointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
