# Generated by Django 5.0.7 on 2024-10-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userappointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alangilanusers',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
