# Generated by Django 5.0.7 on 2024-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_alangilanusers_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userappointment',
            name='date_of_examination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userappointment',
            name='picture_hard_copy',
            field=models.ImageField(blank=True, null=True, upload_to='picture_hard_copys/'),
        ),
        migrations.AddField(
            model_name='userappointment',
            name='position_program_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userappointment',
            name='signature_printed_name_employee_student',
            field=models.ImageField(blank=True, null=True, upload_to='signature_over_printed_name_employee_students/'),
        ),
    ]
